require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AntraegeController do

  # This should return the minimal set of attributes required to create a valid
  # Antraege. As you add validations to Antraege, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "update" => "2013-05-11" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AntraegesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all antraeges as @antraeges" do
      antraege = Antraege.create! valid_attributes
      get :index, {}, valid_session
      assigns(:antraeges).should eq([antraege])
    end
  end

  describe "GET show" do
    it "assigns the requested antraege as @antraege" do
      antraege = Antraege.create! valid_attributes
      get :show, {:id => antraege.to_param}, valid_session
      assigns(:antraege).should eq(antraege)
    end
  end

  describe "GET new" do
    it "assigns a new antraege as @antraege" do
      get :new, {}, valid_session
      assigns(:antraege).should be_a_new(Antraege)
    end
  end

  describe "GET edit" do
    it "assigns the requested antraege as @antraege" do
      antraege = Antraege.create! valid_attributes
      get :edit, {:id => antraege.to_param}, valid_session
      assigns(:antraege).should eq(antraege)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Antraege" do
        expect {
          post :create, {:antraege => valid_attributes}, valid_session
        }.to change(Antraege, :count).by(1)
      end

      it "assigns a newly created antraege as @antraege" do
        post :create, {:antraege => valid_attributes}, valid_session
        assigns(:antraege).should be_a(Antraege)
        assigns(:antraege).should be_persisted
      end

      it "redirects to the created antraege" do
        post :create, {:antraege => valid_attributes}, valid_session
        response.should redirect_to(Antraege.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved antraege as @antraege" do
        # Trigger the behavior that occurs when invalid params are submitted
        Antraege.any_instance.stub(:save).and_return(false)
        post :create, {:antraege => { "update" => "invalid value" }}, valid_session
        assigns(:antraege).should be_a_new(Antraege)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Antraege.any_instance.stub(:save).and_return(false)
        post :create, {:antraege => { "update" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested antraege" do
        antraege = Antraege.create! valid_attributes
        # Assuming there are no other antraeges in the database, this
        # specifies that the Antraege created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Antraege.any_instance.should_receive(:update_attributes).with({ "update" => "2013-05-11" })
        put :update, {:id => antraege.to_param, :antraege => { "update" => "2013-05-11" }}, valid_session
      end

      it "assigns the requested antraege as @antraege" do
        antraege = Antraege.create! valid_attributes
        put :update, {:id => antraege.to_param, :antraege => valid_attributes}, valid_session
        assigns(:antraege).should eq(antraege)
      end

      it "redirects to the antraege" do
        antraege = Antraege.create! valid_attributes
        put :update, {:id => antraege.to_param, :antraege => valid_attributes}, valid_session
        response.should redirect_to(antraege)
      end
    end

    describe "with invalid params" do
      it "assigns the antraege as @antraege" do
        antraege = Antraege.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Antraege.any_instance.stub(:save).and_return(false)
        put :update, {:id => antraege.to_param, :antraege => { "update" => "invalid value" }}, valid_session
        assigns(:antraege).should eq(antraege)
      end

      it "re-renders the 'edit' template" do
        antraege = Antraege.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Antraege.any_instance.stub(:save).and_return(false)
        put :update, {:id => antraege.to_param, :antraege => { "update" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested antraege" do
      antraege = Antraege.create! valid_attributes
      expect {
        delete :destroy, {:id => antraege.to_param}, valid_session
      }.to change(Antraege, :count).by(-1)
    end

    it "redirects to the antraeges list" do
      antraege = Antraege.create! valid_attributes
      delete :destroy, {:id => antraege.to_param}, valid_session
      response.should redirect_to(antraeges_url)
    end
  end

end
